version: '3.1'
services:
  postgresBank:
    image: postgres
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: accountant
      POSTGRES_PASSWORD: development
      POSTGRES_DB: bank
    ports:
      - '5432:5432'
